spring:
  application:
    name: mcc-patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_patient_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=UTC&autoReconnect=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health   # 游녣 endpoint que Consul usar치
        health-check-interval: 10s            # 游녣 cada cu치nto har치 el check
        health-check-critical-timeout: 30s    # 游녣 cu치nto esperar antes de marcarlo "failing"

  rabbitmq:
    image: rabbitmq:4.2-rc-management
    host: localhost
    port: 5672
    username: admin
    password: admin

springdoc:
  api-docs:
    path: /v3/api-docs   # o /api-docs si prefieres
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
server:
  port: 8083
