version: '3.9'
services:

  consul:
    image: hashicorp/consul:1.21
    container_name: consul-hospital
    ports:
      - "8500:8500"   # UI web de Consul
      - "8600:8600/udp" # DNS de Consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -dev -client=0.0.0.0
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-hospital
    ports:
      - "5672:5672"   # Puerto para comunicar microservicios
      - "15672:15672" # Dashboard Web para administración
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped